version: "3"
services:
  express:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - mern-app
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
